<?php

	function m_menu_theme(){
		return array(
			'hepler_menu_history_pasteur' => array(
				'render element' => 'element',
				'template' => 'templates/helper-menu-history-pasteur'
			),
			'helper_menu_left_pasteur' => array(
				'render element' => 'element',
				'template' => 'templates/helper-menu-left-pasteur'
			),
			'helper_menu_health_services' => array(
				'render element' => 'element',
				'template' => 'templates/helper-menu-health-services'
			),
			'helper_menu_health_education' => array(
				'render element' => 'element',
				'template' => 'templates/helper-menu-health-education'
			),
			'helper_menu_public_health' => array(
				'render element' => 'element',
				'template' => 'templates/helper-menu-public-health'
			),
			'helper_menu_scientific_research' => array(
				'render element' => 'element',
				'template' => 'templates/helper-menu-scientific-research'
			),
		);

	}
	
	function m_menu_menu(){
		$items['admin/config/system/menu-helper']=array(
			'title' => t('Helper Menu'),
			'page callback' => 'drupal_get_form',
			'page arguments' => array('m_config_helper_form'),
			'access arguments' => array('administer site configuration'),
		);
		
		 $items['menu_helper/%ctools_js/help_path/%'] = array(
      'title' => t('Helper'),
      'page callback' => 'menu_help_path',
      'page arguments' => array(1,3),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_CALLBACK,
  	);
		return $items;	
	}
	
	function menu_help_path($js=NULL,$menu_name=null){
		if(!$js){
			return _page_menu_help_path($menu_name);	
		}
		
		ctools_include('modal');
  	ctools_include('ajax');
	  $form_state = array(
	    'title' => t('The guide'),
	    'ajax' => TRUE,
	  );
	  
	  $output[] = ctools_modal_command_display(t('Helper to path'),_page_menu_help_path($menu_name));
		print ajax_render($output);
	  exit;
			
	}
	
	function _page_menu_help_path($menu_name){
		$build=array();
		$list_theme_helper_menu=array(
			'menu-history-pasteur' => 'hepler_menu_history_pasteur',
			'menu-left-pasteur' => 'helper_menu_left_pasteur',
			'menu-health-services' => 'helper_menu_health_services',
			'menu-health-education' => 'helper_menu_health_education',
			'menu-public-health' => 'helper_menu_public_health',
			'menu-scientific-research' => 'helper_menu_scientific_research'
		);
		$build['#image_path']=base_path().drupal_get_path('module','m_menu').'/image-helper';
		$build['#theme']=$list_theme_helper_menu[$menu_name];
		return $build;
	}
	
	function m_config_helper_form($form,$form_state){
		$config_helper_form=variable_get('config_helper_form');
		$form['config_helper_form']=array(
			'#title' => t('Setting Helper For Menu'),
			'#type' => 'textarea',
			'#default_value' => $config_helper_form,
			'#description' => t('This is for config of menu. It make the path menu is cleanly')
		);
		
		return system_settings_form($form);
	}
	
	function m_menu_form_menu_edit_item_alter(&$form,&$form_state,$form_id){
		unset($form['i18n']['language']['#options']['und']);
		_load_setting_form_modal();
		$form['link_path']['#description']= t('The path for this menu link. This can be an internal Drupal path such as %add-node or an external URL such as %drupal. Enter %front to link to the front page.', array('%front' => '<front>', '%add-node' => 'node/add', '%drupal' => 'http://drupal.org'));
		$list_theme_helper_menu=array(
			'menu-history-pasteur' ,
			'menu-left-pasteur',
			'menu-health-services' ,
			'menu-health-education',
			'menu-public-health',
			'menu-scientific-research' ,
		);
		if(in_array($form['original_item']['#value']['menu_name'],$list_theme_helper_menu)){
			$form['link_path']['#suffix']='<div class="link_helper">'.ctools_modal_text_button(t('Click here to help the path'), 'menu_helper/nojs/help_path/'.$form['original_item']['#value']['menu_name'], t('Show helper'),  'ctools-modal-ctools-helper-style').'</div>';
		}
	}
	
	function _load_setting_form_modal(){
	  ctools_include('ajax');
	  ctools_include('modal');
	  ctools_modal_add_js();
	
	  $custom_helper_style = array(
	    'ctools-helper-style' => array(
	      'modalSize' => array(
	        'type' => 'fixed',
	        'width' => 900,
	        'height' => 400,
	        'addWidth' => 20,
	        'addHeight' => 15,
	      ),
	      'modalOptions' => array(
	        'opacity' => .5,
	        'background-color' => '#000',
	      ),
	      'animation' => 'fadeIn',
	      'modalTheme' => 'CToolsHelperModal',
	      'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'm_menu'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
	    ),
	  );

  	drupal_add_js($custom_helper_style, 'setting');
  	ctools_add_js('ctools-modal', 'm_menu');
  	ctools_add_css('ctools-modal', 'm_menu');	
	}
	
