<?php

	function m_health_service_menu(){
		 $items['health-service']=array(
	  	'page callback' => 'health_service_first_show',
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );

	  return $items;
	}

	function m_health_service_node_view($node, $view_mode, $langcode){
		if($node->type =='health_services' && $view_mode == 'full'){
			#menu_tree_set_path('menu-top-header', 'health-service');
			$files=field_get_items('node', $node, 'field_health_services_file');
			$images=field_get_items('node', $node, 'field_health_services_image');
			$node->content['file_download']='';
			if($files){
				$file_list='';
				foreach($files as $key => $file){
					$file_list.='<li '.( $key == 0 ? 'class="first"' : '').'>';
					$file_list.='<a title="'.$file['description'].'" class="title1" href="#">'.$file['description'].'</a>';
					$file_list.='<a title="'.$file['description'].'" class="float-r" href="'.file_create_url($file['uri']).'">'.t('Download').'</a>';
					$file_list.='</li>';
				}

				$node->content['file_download']=array(
					'#markup' => $file_list
				);
			}

			$node->content['images']='';
			if($images){
				$image_list='';
				foreach($images as $image){
		 	 		$image_list.='<li>';
		 	 		$image_list.='<img src="'.image_style_url('image_240px_150px',$image['uri']).'" alt="'.$image['alt'].'" />';
		 	 		$image_list.='<p>'.$image['title'].'</p>';
		 	 		$image_list.='</li>';
		 	 	}
		 	 	$node->content['images']=$image_list;
			}

			 $summary=field_get_items('node', $node, 'body');
			 $node->content['summary']='';
			 if($summary[0]['summary'] != ''){
			 	$summary = field_view_value('node', $node, 'body', $summary[0],'teaser');
			 	$node->content['summary']=$summary;
			 }
		}
	}

	function health_service_first_show(){
		$menu_tree = i18n_menu_translated_tree('menu-health-services');
		if(count($menu_tree) == 0 ){
			drupal_goto();
		}
		reset($menu_tree);
		$k=key($menu_tree);
                
		if(isset($menu_tree[$k]['#original_link'])){
			drupal_goto($menu_tree[$k]['#original_link']['link_path']);
		}
	}

