<?php

function homepage_boot()
{
    global $user, $language;

    $arg = arg();
    if (!$user->uid && preg_match('/^admin(\/.*)?/i', $_GET['q'])) {

        $_SESSION['REDIRECT_URL'] = $_GET['q'];
        header('Location: ' . $GLOBALS['base_url'] . '/user');
        exit;
    }
    if (!$user->uid && (arg(1)) && arg(1) == 'admin' && !arg(2)) {

        $_SESSION['REDIRECT_URL'] = $_GET['q'];
        header('Location: ' . $GLOBALS['base_url'] . '/' . arg(0) . '/user');
        exit;
    }
    if (!empty($user->uid) && $_GET['q'] == 'user' || !empty($user->uid) && arg(0) == 'admin' && !arg(1)) {
        header('Location: ' . $GLOBALS['base_url'] . '/admin/dashboard');
        exit;
    }
    if (!empty($user->uid) && arg(1) == 'admin' && !arg(2)) {
        header('Location: ' . $GLOBALS['base_url'] . '/' . $arg[0] . '/admin/dashboard');
        exit;
    }
}

function homepage_user_login(&$edit, $account)
{
    if ($account->uid == 1) {
        drupal_goto('admin');
    } elseif (array_key_exists(4, $account->roles)) {
        drupal_goto('admin/dashboard');
    }
}

function homepage_form_alter(&$form, &$form_state, $form_id)
{
    switch ($form_id) {
        case 'health_education_node_form':
        case 'health_services_node_form':
        case 'links_website_node_form':
        case 'news_node_form':
        case 'pasteur_history_node_form':
        case 'pasteur_institute_node_form':
        case 'public_health_node_form':
        case 'publications_node_form':
        case 'recruitment_node_form':
        case 'scientific_research_node_form':
            $form['#action'] .= '?destination=admin/content';
            break;
    }
}

function homepage_menu()
{
    $items['admin/links'] = array(
        'title' => t('Link All'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('get_list_link_form'),
        'access arguments' => array('access content'),
    );
    $items['admin/links/list'] = array(
        'title' => t('List'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => - 10,
    );

    $items['admin/links/%node/edit'] = array(
        'title' => 'Edit',
        'page callback' => 'node_page_edit',
        'page arguments' => array(2),
        'access callback' => 'node_access',
        'access arguments' => array('update', 2),
        'weight' => 0,
        'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
        'file path' => drupal_get_path('module', 'node'),
        'file' => 'node.pages.inc',
    );
    $items['admin/links/add'] = array(
        'title' => t('Add new'),
        'description' => 'Add new',
        'page callback' => 'node_add',
        'page arguments' => array('links_website'), //banner_rotation get name content type
        'access callback' => 'node_access',
        'access arguments' => array('create', 'links_website'),
        'file path' => drupal_get_path('module', 'node'),
        'file' => 'node.pages.inc',
        //'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
        'type' => MENU_LOCAL_ACTION,
        'weight' => 1
    );
    return $items;
}

function get_list_link_form($form, &$form_state)
{
    $type = 'links_website';
    $destination = drupal_get_destination();
    $header = array(
        'title' => array('data' => t('Title'), 'field' => 'title'),
        'url' => array('data' => t('URL'), 'field' => 'field_links_value'),
        'publish' => array('data' => t('Publish'), 'field' => 'status'),
    );
    $header['operations'] = array('data' => t('Actions'));

    $query = db_select('node', 'n')->extend('PagerDefault')->extend('TableSort');
    $query->leftjoin('field_revision_field_links', 'url', 'n.vid=url.revision_id and n.type=url.bundle');
    $query->fields('n', array('nid', 'title', 'status'));
    $query->fields('url', array('field_links_value'));
    $query->condition('type', $type);
    $query->orderByHeader($header);
    $items = $query->execute()->fetchAll();
    $options = array();
    if (!empty($items)) {
        foreach ($items as $item) {
            $options[$item->nid] = array(
                'title' => isset($item->title) ? $item->title : '',
                'url' => isset($item->field_links_value) ? $item->field_links_value : '',
                'publish' => $item->status == 1 ? 'yes' : 'false',
                'operations' => l(t('Edit'), 'admin/links/' . $item->nid . '/edit', array('query' => $destination)),
            );
        }
    }
    $form['text']['#prefix'] = '<div style="padding:30px 10px 10px 10px">';
    $form['list'] = array(
        '#theme' => 'table',
        '#header' => $header,
        '#rows' => $options,
        '#empty' => t('No content available.')
    );
    $form['pager'] = array('#markup' => theme('pager'));
    $form['#suffix'] = '</div>';
    return $form;
}

function add_links_form($form, &$form_state)
{

}

?>