<?php

	function m_health_education_theme(){
		return array(
			'm_health_education' => array(
				'template' => 'templates/m-health-education',
				'render element' => 'element'
			),
		);	
	}

	function m_health_education_menu() {
	  $items['<health_education>'] = array(
	    'page callback' => '_menu_health_education',
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
	  
	  $items['health-education'] = array(
	    'page callback' => 'health_education_show_first',
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	    'file' => 'm_health_education.page.inc'
	  );
	  
	  $items['health-education/%m_menu_edu']=array(
	  	'page callback' => 'show_sub_menu',
	  	'page arguments' => array(1),
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	    'file' => 'm_health_education.page.inc'
	  );
	  
	  return $items;
	}
	
	
	function m_menu_edu_load($mlid){
		$item=menu_link_load($mlid);	
		
		if($item['menu_name'] != 'menu-health-education'){
			return false;	
		}
		
		if((isset($item['localized_options']['langcode']) && $item['localized_options']['langcode'] != i18n_langcode())
				|| $item['hidden']==1){
			return false;
		}
		return $item;
	}
	
	
	
	function _menu_health_education(){
		drupal_not_found();	
	}
	
	
	function m_health_education_menu_link_alter(&$item, $menu) {
	  if (@$item['module'] == 'menu') {
	    if ($item['link_path'] == '<health_education>') {
	      $item['options']['alter'] = TRUE;
	      $item['options']['unaltered_hidden'] = $item['hidden'];
	      $item['options']['external'] = TRUE;
	    }
	    else {
	      unset($item['options']['unaltered_hidden']);
	    }
	  }
	}

	function m_health_education_translated_menu_link_alter(&$item, $map) {
	   if ($item['module'] == 'menu') {
		    $href = $item['href'];
		    $item['options']['alter'] = TRUE;
		    if ($item['link_path'] == '<health_education>') {
		    	$href=url('health-education/'.$item['mlid']);
		    	if($item['mlid'] === arg(1)){
		      	$item['in_active_trail']=TRUE;
		    	}
		    }else {
		      unset($item['options']['unaltered_hidden']);
		    }
		    $item['href'] = $href;
		  }
	}

	
	function m_health_education_node_view($node, $view_mode, $langcode){
		if($node->type =='health_education' && $view_mode == 'full'){
			
			$images=field_get_items('node', $node, 'field_health_education_image');
			$file=field_get_items('node', $node, 'field_health_education_file');
			
			$node->content['file_download']='';
			if($file){
				$node->content['file_download']=array(
					'#markup' => '<li><a target="_blank" href="'.file_create_url($file[0]['uri']).'" title="'.t('Download').'">'.t('Download').'</a></li>'
				);
			}
			$node->content['images']='';
			if($images){
				$image_list='';
				foreach($images as $image){
		 	 		$image_list.='<li>';
		 	 		$image_list.='<img src="'.image_style_url('image_240px_150px',$image['uri']).'" alt="'.$image['alt'].'" />';
		 	 		$image_list.='<p>'.$image['title'].'</p>';
		 	 		$image_list.='</li>';
		 	 	}	
		 	 	$node->content['images']=$image_list;
			}
	
			$show_other_node=field_get_items('node',$node,'field_he_show_other_article');
			
			
			$node->show_other_node=false;
			$node->content['other_node']='';
			
			if($show_other_node){
				$term_name=field_get_items('node',$node,'field_health_education_cat');

				if($term_name){
					$term=taxonomy_term_load($term_name[0]['tid']);
					$node->content['term_name']=check_plain($term->name);
					if($nids=taxonomy_select_nodes($term->tid, FALSE ,FALSE, array('t.sticky' => 'DESC', 't.created' => 'ASC'))){
						$nodes = node_load_multiple($nids);
						$node_other='
						<div class="list-disease">
						<div class="rnd tl"></div>
						<div class="rnd tr"></div>
						<div class="rnd bl"></div>
						<div class="rnd br"></div>
						<div class="rnd tm"></div>
						<div class="rnd bm"></div>
						<div class="rnd lm"></div>
						<div class="rnd rm"></div>
						<ul class="inner-list-disease">';
						foreach($nodes as $_node){
							$class='';
							if($_node->nid == $node->nid){
								$class="current";	
							}
							$node_other.='<li class="'.$class.'"><a href="'.url('node/'.$_node->nid).'" title="'.check_plain($_node->title).'">'.check_plain($_node->title).'</a></li>';
						}
						$node->content['other_node']=$node_other.'</ul></div>';
						$node->show_other_node=true;
					}
				}
			}
			
			$summary=field_get_items('node', $node, 'body');
			$node->content['summary']='';
			if($summary[0]['summary'] != ''){
			 $summary = field_view_value('node', $node, 'body', $summary[0],'teaser');
			 $node->content['summary']=$summary;
			}
			
			
		}
	}
	
	# BEGIN :hook block 

	function m_health_education_block_info(){
		$blocks=array();
		$blocks['health_education_left'] = array(
	    'info' => t('Block Menu At Health Education'),
	    'status' => TRUE,
	    'region' => 'sidebar_left', 
	    'visibility' => BLOCK_VISIBILITY_LISTED,  
	    'pages' => 'health-education/nhealth-education/*', 
	  );
		return	$blocks;
	}
	
	
	function m_health_education_block_view($block_name = ''){
		global $language;
		switch ($block_name) {
	    case 'health_education_left':
	 
	    	$tree = menu_tree_page_data('menu-health-education',1);
    	  $tree = i18n_menu_localize_tree($tree, i18n_langcode());
    	
	    	$content=menu_tree_output($tree);
	    	$content['#theme_wrappers']=array('menu_tree_block_left');
	      $block['content'] =  $content;
	      break;
	  }
	  return $block;
	}
	
	# END :hook block