<?php

function m_scientific_research_theme()
{
    return array(
        'm_scientific_research' => array(
            'template' => 'templates/m-scientific-research',
            'render element' => 'element'
        ),
    );

}

function m_scientific_research_menu()
{
    $items['<scientific_research>'] = array(
        'page callback' => '_menu_scientific_research',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['scientific-research/%m_menu_sceintific'] = array(
        'page callback' => 'show_sub_menu',
        'page arguments' => array(1),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
        'file' => 'm_scientific_research.page.inc'
    );

    $items['scientific-research'] = array(
        'page callback' => 'scientific_research_show_first',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
        'file' => 'm_scientific_research.page.inc'
    );

    return $items;
}

function m_menu_sceintific_load($mlid)
{
    $item = menu_link_load($mlid);

    if ($item['menu_name'] != 'menu-scientific-research') {
        return false;
    }

    if ((isset($item['localized_options']['langcode']) && $item['localized_options']['langcode'] != i18n_langcode()) || $item['hidden'] == 1) {
        return false;
    }
    return $item;
}

function _menu_scientific_research()
{
    drupal_not_found();
}

function m_scientific_research_menu_link_alter(&$item, $menu)
{
    if (@$item['module'] == 'menu') {
        if ($item['link_path'] == '<scientific_research>') {
            $item['options']['alter'] = TRUE;
            $item['options']['unaltered_hidden'] = $item['hidden'];
            $item['options']['external'] = TRUE;
        } else {
            unset($item['options']['unaltered_hidden']);
        }
    }
}

function m_scientific_research_translated_menu_link_alter(&$item, $map)
{
    if ($item['module'] == 'menu') {
        $href = $item['href'];
        $item['options']['alter'] = TRUE;
        $item['options']['external'] = TRUE;

        if ($item['link_path'] == '<scientific_research>') {
            $href = url('scientific-research/'.$item['mlid']);
            if ($item['mlid'] === arg(1)) {
                $item['in_active_trail'] = TRUE;
            }
        } else {
            unset($item['options']['unaltered_hidden']);
        }
        $item['href'] = $href;

    }
}

function m_scientific_research_node_view($node, $view_mode, $langcode)
{
    if ($node->type == 'scientific_research' && $view_mode == 'full') {
        $images = field_get_items('node', $node, 'field_scientific_research_image');
        $file = field_get_items('node', $node, 'field_scientific_research_file');
        $node->content['file_download'] = '';
        if ($file) {
            $node->content['file_download'] = array(
                '#markup' => '<li><a target="_blank" href="'.file_create_url($file[0]['uri']).'" title="'.t('Download').'">'.t('Download').'</a></li>'
            );
        }
        $node->content['images'] = '';
        if ($images) {
            $image_list = '';
            foreach ($images as $image) {
                $image_list .= '<li>';
                $image_list .= '<img src="'.image_style_url('image_240px_150px', $image['uri']).'" alt="'.$image['alt'].'" />';
                $image_list .= '<p>'.$image['title'].'</p>';
                $image_list .= '</li>';
            }
            $node->content['images'] = $image_list;
        }

        $summary = field_get_items('node', $node, 'body');
        $node->content['summary'] = '';
        if ($summary[0]['summary'] != '') {
            $summary = field_view_value('node', $node, 'body', $summary[0], 'teaser');
            $node->content['summary'] = $summary;
        }
    }
}

# BEGIN :hook block

function m_scientific_research_block_info()
{
    $blocks = array();
    $blocks['scientific_research_left'] = array(
        'info' => t('Block Menu At Scientific Researcg'),
        'status' => TRUE,
        'region' => 'sidebar_left',
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => implode("\n", array(
            'scientific-research/*',
            'scientific-research/',
        )),
    );
    return $blocks;
}

function m_scientific_research_block_view($block_name = '')
{
    global $language;
    switch ($block_name) {
    case 'scientific_research_left':
        
        $tree = menu_tree_page_data('menu-scientific-research', 1);
        $tree = i18n_menu_localize_tree($tree, i18n_langcode());
        $content = menu_tree_output($tree);
        $content['#theme_wrappers'] = array('menu_tree_block_left');
        $block['content'] = $content;
        break;
    }
    return $block;
}
# END :hook block