<?php

	function m_public_health_theme(){
		return array(
			'm_public_health' => array(
				'template' => 'templates/m-public-health',
				'render element' => 'element'
			),
		);	
		
	}

	function m_public_health_menu() {
	  $items['<public_health>'] = array(
	    'page callback' => '_menu_public_health',
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
	  
	  $items['public-health/%m_menu']=array(
	  	'page callback' => 'show_sub_menu',
	  	'page arguments' => array(1),
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	    'file' => 'm_public_health.page.inc'
	  );
	  
	  $items['public-health']=array(
	  	'page callback' => 'public_health_first_show',
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	    'file' => 'm_public_health.page.inc'
	  );
	  
	  return $items;
	}
	
	
	function m_menu_load($mlid){
		$item=menu_link_load($mlid);	
		
		if($item['menu_name'] != 'menu-public-health'){
			return false;	
		}
		if((isset($item['localized_options']['langcode']) && $item['localized_options']['langcode'] != i18n_langcode())
				|| $item['hidden']==1){
			return false;
		}
		return $item;
	}
	
	
	
	function _menu_public_health(){
		drupal_not_found();	
	}
	
	function m_public_health_menu_link_alter(&$item, $menu) {
	  if (@$item['module'] == 'menu') {
	    if ($item['link_path'] == '<public_health>') {
	      $item['options']['alter'] = TRUE;
	      $item['options']['unaltered_hidden'] = $item['hidden'];
	      $item['options']['external'] = TRUE;
	    }
	    else {
	      unset($item['options']['unaltered_hidden']);
	    }
	  }
	}
	
	function m_public_health_translated_menu_link_alter(&$item, $map) {
	   if ($item['module'] == 'menu') {
		    $href = $item['href'];
		    $item['options']['alter'] = TRUE;
		    $item['options']['external'] = TRUE;
		    
		    if ($item['link_path'] == '<public_health>') {
		      $href = url('public-health/'.$item['mlid']);   
		      if($item['mlid'] === arg(1)){
		      	$item['in_active_trail']=TRUE;
		    	}
		    }else {
		      unset($item['options']['unaltered_hidden']);
		    }
		    $item['href'] = $href;
		  }
	}
	
	
	function m_public_health_node_view($node, $view_mode, $langcode){
		if($node->type =='public_health' && $view_mode == 'full'){
			$images=field_get_items('node', $node, 'field_public_health_image');
			$file=field_get_items('node', $node, 'field_public_health_file');
			$node->content['file_download']='';
			if($file){
				$node->content['file_download']=array(
					'#markup' => '<li><a target="_blank" href="'.file_create_url($file[0]['uri']).'" title="'.t('Download').'">'.t('Download').'</a></li>'
				);
			}
			$node->content['images']='';
			if($images){
				$image_list='';
				foreach($images as $image){
		 	 		$image_list.='<li>';
		 	 		$image_list.='<img src="'.image_style_url('image_240px_150px',$image['uri']).'" alt="'.$image['alt'].'" />';
		 	 		$image_list.='<p>'.$image['title'].'</p>';
		 	 		$image_list.='</li>';
		 	 	}	
		 	 	$node->content['images']=$image_list;
			}
			
			$summary=field_get_items('node', $node, 'body');
			$node->content['summary']='';
			if($summary[0]['summary'] != ''){
			 $summary = field_view_value('node', $node, 'body', $summary[0],'teaser');
			 $node->content['summary']=$summary;
			}
		}
	}
	
	# BEGIN :hook block 

	function m_public_health_block_info(){
		$blocks=array();
		$blocks['public_health_left'] = array(
	    'info' => t('Block Menu At Public Health'),
	    'status' => TRUE,
	    'region' => 'sidebar_left', 
	    'visibility' => BLOCK_VISIBILITY_LISTED,  
	    'pages' => 'public-health\npublic-health/*', 
	  );
		return	$blocks;
	}
	
	function m_public_health_block_view($block_name = ''){
		global $language;
		switch ($block_name) {
	    case 'public_health_left':
	    	$tree = menu_tree_page_data('menu-public-health',1);
    	  $tree = i18n_menu_localize_tree($tree, i18n_langcode());
	    	$content=menu_tree_output($tree);
	    	$content['#theme_wrappers']=array('menu_tree_block_left');
	      $block['content'] =  $content;
	    break;
	  }
	  return $block;
	}
	# END :hook block